version: "3"
services:

  server:
    image: nordnetpy.azurecr.io/nordnetpy:v1
    container_name: flask
    ports: ['80:5000']
    volumes: ['.:/usr/src/app']
    restart: always
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: animtel
      DB_PASSWORD: w2e3r4T5
      DB_DATABASE: TutAPI
      DB_HOST: database
    links:
      - database

  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: TutAPI
      MYSQL_USER: animtel
      MYSQL_PASSWORD: w2e3r4T5
      MYSQL_ROOT_PASSWORD: w2e3r4T5
    ports:
      - '5005:3306'
    expose:
      - '5005'
    volumes:
      - flask-db:/var/lib/mysql

volumes:
  flask-db:
